### Masking and Boolean Operations

In [2]:
import numpy as np

x = np.random.rand(10)
print(x)

[0.03440185 0.97683568 0.70163932 0.73941315 0.7368392  0.07552595
 0.4347054  0.24832353 0.08794376 0.00560737]


In [11]:
# boolean operation 
x > 0.5

array([False, False, False,  True, False,  True,  True,  True,  True,
        True])

In [12]:
x.mean()

0.5571173485632726

In [13]:
# фильтрация
x[x > 0.5]

array([0.86177407, 0.65177809, 0.77202475, 0.85794082, 0.59029321,
       0.76590412])

In [14]:
# маскирование
x[x < 0.5] = 0.5
x

array([0.5       , 0.5       , 0.5       , 0.86177407, 0.5       ,
       0.65177809, 0.77202475, 0.85794082, 0.59029321, 0.76590412])

In [17]:
x = np.random.rand(10)
print(x)

[0.82747211 0.61015749 0.1517501  0.65938944 0.90646299 0.81052509
 0.33436329 0.09309347 0.60506755 0.33590571]


In [4]:
a = np.array([np.random.randint(1,10) for i in range(5)])
print(a)

[7 4 9 4 1]


In [5]:
np.where(a<3, 'less than 3', 'bigger or eqaul to 3')

array(['bigger or eqaul to 3', 'bigger or eqaul to 3',
       'bigger or eqaul to 3', 'bigger or eqaul to 3', 'less than 3'],
      dtype='<U20')

In [5]:
#1
def TransportVersion(arr):
    return arr.T

x2 = np.array([[2,5],[3,7]])
print(x2)
print(TransportVersion(x2))



[[2 5]
 [3 7]]
[[2 3]
 [5 7]]


In [23]:
#2
x = np.random.rand(30)
randomList=[]

for i in range(10):
    randomList.append(np.random.choice(x)) 
x2=np.array(randomList)
print(x2.mean())
print(x2.sum())

0.4502401914222497
4.502401914222497


In [6]:
#3
randomList=[]
for i in range(10):
    randomList.append(np.random.randint(0,100)) 
print(randomList)
x=np.array(randomList)
print(len(x[x > 50]))
np.where(x<18, 'baby', np.where(x<60, 'adult', 'elder'))


[60, 72, 35, 46, 74, 19, 81, 47, 79, 32]
5


array(['elder', 'elder', 'adult', 'adult', 'elder', 'adult', 'elder',
       'adult', 'elder', 'adult'], dtype='<U5')

In [35]:
# ДЗ
#1
n=int(input())

arr=np.array([[np.random.randint(1,10) for i in range(n)] for i in range(n)])
print(arr)
a=sum(arr[i][n-i-1] for i in range(n))
my_sum = [(arr[i][i]) for i in range(arr.shape[0])]
print(a+sum(my_sum))


3
[[8 6 5]
 [1 2 4]
 [7 2 7]]
31
