### Начало работы 

In [1]:
import numpy as np
a = np.array(3)
print(a)

3


In [2]:
type(a)

numpy.ndarray

In [3]:
a.ndim
# 0 мерный список


0

In [4]:
b = np.array([3])
print(b)
print(b.ndim)

[3]
1


In [5]:
c = np.array([[3]])
print(c)
print(c.ndim)


[[3]]
2


In [6]:
c[0][0]


3

### Индексирование 

In [7]:
d = np.array([[[1,9], [2,3]], [[4,5],[6,7]]])
print(d)
print(d.ndim)

[[[1 9]
  [2 3]]

 [[4 5]
  [6 7]]]
3


In [11]:
d[0, 1, 1]

3

In [12]:
d[0, 1, 1]

3

In [13]:
d[1, 0, 1]


5

In [14]:
d[-1, -1, 0]


6

### Слайсы

In [15]:
d



array([[[1, 9],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
d[0, 0]


array([1, 9])

In [17]:
d[:1, :1, :]


array([[[1, 9]]])

In [18]:
d[1:, :, 1:]

array([[[5],
        [7]]])

In [19]:
d[:, :, 1:]


array([[[9],
        [3]],

       [[5],
        [7]]])

### Агрегирование

In [20]:
d

array([[[1, 9],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
# списки NumPy
d.max()


9

In [22]:
d.sum()



37

In [23]:
d.size


8

In [24]:
# среднее чисел в массиве d
d.mean()


4.625

### Криптография

In [25]:
message = 'I AM HERE'
message_num = '9 27 1 13 27 8 5 18 5'
a1 = np.array([9, 27, 1])
a2 = np.array([13, 27, 8])
a3 = np.array([5, 18, 5])

In [26]:
A = np.array([[1,1,0], [2,0,1], [1,0,0]])
print(A)
# ключ


[[1 1 0]
 [2 0 1]
 [1 0 0]]


### Зашифровка

In [27]:
a1_enc = np.dot(A, a1)
a1_enc
# 3x3 3x1 => 3x1

array([36, 19,  9])

In [28]:
a2_enc = np.dot(A, a2)
a2_enc

array([40, 34, 13])

In [29]:
a3_enc = np.dot(A, a3)
a3_enc


array([23, 15,  5])

In [30]:
message_encrypted = np.concatenate([a1_enc, a2_enc, a3_enc])
print(message_encrypted)
# зашифрованное сообщение

[36 19  9 40 34 13 23 15  5]


In [15]:
# inv - inverse - обратная
from scipy.linalg import inv
A_inv = inv(A)
print(A_inv)
# A -> A_inv
# A_inv -> A


[[-0.  0.  1.]
 [ 1.  0. -1.]
 [ 0.  1. -2.]]


In [32]:
# разбили на 3 элемента
b = np.split(message_encrypted, 3)
print(b[0])
# с помощью матричного умножения расшифровываем
b1 = np.dot(A_inv, b[0])
print(b1)


[36 19  9]
[ 9. 27.  1.]


In [33]:
print(b[1])
b2 = np.dot(A_inv, b[1])
print(b2)

[40 34 13]
[13. 27.  8.]


In [34]:
print(b[2])
b3 = np.dot(A_inv, b[2])
print(b3)

[23 15  5]
[ 5. 18.  5.]


In [36]:
message_decrypted = np.concatenate([b1, b2, b3])
print(message_decrypted)


[ 9. 27.  1. 13. 27.  8.  5. 18.  5.]


### Практическая работа 

In [6]:
#1
import random as rand
n=int(input())
test_arr=np.array([i for i in range(1, n+1)])
arr=np.array([rand.randint(1, n) for i in range(n)])
result = np.in1d(test_arr, arr).all()
print(result)

3
False


In [135]:
#3
def happyNumber(m, n):
    arr=np.array([[rand.randint(1,100) for i in range(n)] for i in range(m)])
    happyNumbers=[]
    check=True
    for i in range(arr.shape[0]):
        theSmallestNumberInTheRow=min(arr[i])
        check=True
        for j in range(arr.shape[0]):
            if(theSmallestNumberInTheRow<arr[j,0]):
                check=False       
        if(check==True):
            happyNumbers.append(theSmallestNumberInTheRow)
    
    print(arr)       
    return happyNumbers
    

print(happyNumber(3,2))


[[ 9 25]
 [96 98]
 [74 66]]
[96]


In [4]:
#5
#Используйте следующую матрицу B чтобы зашифровать сообщение “PROF IS BORING”
letters = 'abcdefghijklmnopqrstuvwxyz '
numbers = np.arange(1, len(letters)+1)
text='prof is boring'

def letter_to_number(text, letters=letters, numbers=numbers):
    list1 = []
    for i in text:
        ind = letters.find(i)
        list1.append(numbers[ind])
    return list1

numArray=letter_to_number(text)

def number_to_text(num_array, letters, numbers):
    list1 = []
    for i in num_array:
        ind = numbers[i-1]
        list1.append(letters[ind-1])
    return list1

print(number_to_text(numArray, letters, numbers))

A = np.array([[2,3,2], [1,4,2], [5,2,3]])




['p', 'r', 'o', 'f', ' ', 'i', 's', ' ', 'b', 'o', 'r', 'i', 'n', 'g']


In [9]:
#ДЗ

#1
arr=np.array([rand.randint(1, 100) for i in range(5)])
print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.ndim)
print(arr.std())


[78 21 54 15 19]
15
78
187
1
24.630062931304092


In [18]:
#2
message = 'i love you'
numbers = np.arange(1, len(letters)+1)
numArray=letter_to_number(message)


a1 = np.array([9, 27, 12])
a2 = np.array([15, 22, 5])
a3 = np.array([27, 25, 15])
a4=np.array([21, 0, 0])

A = np.array([[1,1,0], [2,0,1], [1,0,0]])

a1_enc = np.dot(A, a1)
a2_enc = np.dot(A, a2)
a3_enc = np.dot(A, a3)
a4_enc = np.dot(A, a4)

message_encrypted = np.concatenate([a1_enc, a2_enc, a3_enc, a4_enc])


A_inv = inv(A)

b = np.split(message_encrypted, 4)
b1 = np.dot(A_inv, b[0])
b2 = np.dot(A_inv, b[1])
b3 = np.dot(A_inv, b[2])
b4=np.dot(A_inv, b[3])

message_decrypted = np.concatenate([b1, b2, b3, b4])
print(message_decrypted)




[ 9. 27. 12. 15. 22.  5. 27. 25. 15. 21.  0.  0.]
