### Маскирование и булевые операции

In [1]:
import numpy as np

x = np.random.rand(10)
print(x)

[0.16339933 0.24853185 0.88350542 0.39512653 0.27551514 0.98907531
 0.31017006 0.8189136  0.10820783 0.10279997]


In [11]:
# булевые операции (логические операции)
x > 0.5

array([False, False, False,  True, False,  True,  True,  True,  True,
        True])

In [12]:
x.mean()

0.5571173485632726

In [13]:
# фильтрация
x[x > 0.5]

array([0.86177407, 0.65177809, 0.77202475, 0.85794082, 0.59029321,
       0.76590412])

In [14]:
# маскирование
x[x < 0.5] = 0.5
x

array([0.5       , 0.5       , 0.5       , 0.86177407, 0.5       ,
       0.65177809, 0.77202475, 0.85794082, 0.59029321, 0.76590412])

In [17]:
x = np.random.rand(10)
print(x)

[0.82747211 0.61015749 0.1517501  0.65938944 0.90646299 0.81052509
 0.33436329 0.09309347 0.60506755 0.33590571]


In [20]:
a = np.array([np.random.randint(1,10) for i in range(5)])
print(a)

[6 6 3 4 2]


In [25]:
np.where(a<3, 'меньше 3', 'больше или равен 3')

array(['больше или равен 3', 'больше или равен 3', 'больше или равен 3',
       'больше или равен 3', 'меньше 3'], dtype='<U18')

In [5]:
#1
def TransportVersion(arr):
    return arr.T

x2 = np.array([[2,5],[3,7]])
print(x2)
print(TransportVersion(x2))



[[2 5]
 [3 7]]
[[2 3]
 [5 7]]


In [23]:
#2
x = np.random.rand(30)
randomList=[]

for i in range(10):
    randomList.append(np.random.choice(x)) 
x2=np.array(randomList)
print(x2.mean())
print(x2.sum())

0.4502401914222497
4.502401914222497


In [16]:
#3
randomList=[]
for i in range(10):
    randomList.append(np.random.randint(0,100)) 
print(randomList)
x=np.array(randomList)
print(len(x[x > 50]))
np.where(x<18, 'ребенок', np.where(x<60, 'взрослый человек', 'пожилой'))


[49, 3, 59, 81, 93, 48, 29, 73, 75, 77]
6


array(['взрослый человек', 'ребенок', 'взрослый человек', 'пожилой',
       'пожилой', 'взрослый человек', 'взрослый человек', 'пожилой',
       'пожилой', 'пожилой'], dtype='<U16')

In [35]:
# ДЗ
#1
n=int(input())

arr=np.array([[np.random.randint(1,10) for i in range(n)] for i in range(n)])
print(arr)
a=sum(arr[i][n-i-1] for i in range(n))
my_sum = [(arr[i][i]) for i in range(arr.shape[0])]
print(a+sum(my_sum))


3
[[8 6 5]
 [1 2 4]
 [7 2 7]]
31
